/*
  Main Module Definition.
  - We will be using RoC reverse control pattern for better flexisblity
  - The main module is UN-AWARE of any of its dependinces except of 3rd party

  *Rules

  - DO NOT EDIT THIS FILE UNLESS ALL TEAM AGREE THAT ADDING A NEW 3rd PARTY
    DEPENDENCY TO APP IS OKAY BY EVERY ONE
  - All Modules should inherit from this main module
  - All Modules should declare its own Config and Run code blocks,
    Angular will take care of running them all.
  - Keep this module Clean, only Global Configurtion should be set here
*/
(function(angular) {
  'use strict';

  angular.module('webtrekk', [
    'ui.router'
  ])
  .config(function($urlServiceProvider, $locationProvider) {
    "ngInject";
    $locationProvider.html5Mode(true);
  }); // use it to inject global 3rd parties

})(angular);
