/*
  Main Module Definition.
  - We will be using RoC reverse control pattern for better flexisblity
  - The main module is UN-AWARE of any of its dependinces except of 3rd party

  *Rules

  - DO NOT EDIT THIS FILE, this is used to:-
    1. define 3rd party libraries
    2. set module global configs
  - All Modules should inherit from this main module
  - All Modules should declare its own Config and Run code blocks,
  - Remember: our build system will include all .js files inside /src folder
  - Index route should declare itself as soo in its own .config block
*/
(function(angular) {
  /**
   * @namespace Webtrekk_demo
   */
  angular.module('webtrekk', [
    'ui.router',
    // uncomment following if you gona use AMD tool
    // require('./services').name,
    // require('./details').name,
    // require('./main').name,
    // require('./navi').name,
  ])
    .constant('example', 'global-config-value')
    .config(($locationProvider) => {
      'ngInject';

      $locationProvider.html5Mode(true);
    // ... other configurations
    });
}(angular));
